# 
# @path src/main/resources/application-prod.yml
# @description Configuration production (BDD distante, fichiers secrets)
---
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
