# 
# @path src/main/resources/application-dev.yml
# @description Configuration dev ultra-robuste avec récupération de clé publique
---
spring:
  datasource:
    url: jdbc:mysql://db:3306/gc_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      continue-on-error: true

  flyway:
    enabled: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false

server:
  port: 8080

logging:
  level:
    com.example.gestioncommerciale: DEBUG
    org.springframework.security: DEBUG
